// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy12WBGIA8CZVfhvfGgCNwjLYYE8Dsi-E',
    appId: '1:890430890610:web:f24aa4e76464fa26a258eb',
    messagingSenderId: '890430890610',
    projectId: 'habitgo-12ecf',
    authDomain: 'habitgo-12ecf.firebaseapp.com',
    storageBucket: 'habitgo-12ecf.firebasestorage.app',
    measurementId: 'G-J4FWX4YLXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJtTifhiTBS_9QAnw4ZD8YQeXKFmrL7zo',
    appId: '1:890430890610:android:fcb6f2ae5ad445fea258eb',
    messagingSenderId: '890430890610',
    projectId: 'habitgo-12ecf',
    storageBucket: 'habitgo-12ecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy12WBGIA8CZVfhvfGgCNwjLYYE8Dsi-E',
    appId: '1:890430890610:web:f24aa4e76464fa26a258eb',
    messagingSenderId: '890430890610',
    projectId: 'habitgo-12ecf',
    storageBucket: 'habitgo-12ecf.firebasestorage.app',
    iosBundleId: 'com.example.habitgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy12WBGIA8CZVfhvfGgCNwjLYYE8Dsi-E',
    appId: '1:890430890610:web:f24aa4e76464fa26a258eb',
    messagingSenderId: '890430890610',
    projectId: 'habitgo-12ecf',
    storageBucket: 'habitgo-12ecf.firebasestorage.app',
    iosBundleId: 'com.example.habitgo',
  );
}
